// Write one static HTML page per venue view (public/cellar.html, ...) and
// public/sitemap.xml, both from VIEW_META in src/init.js.
//
// Why: every venue path used to be a vercel.json rewrite to the one
// index.html, whose raw head says canonical = https://tonightnyc.com. Google
// reads the raw head, so it filed /cellar, /stand, ... as copies of the home
// page and never indexed them. syncUrlToSource() fixes title + canonical only
// in JS. Each venue page is index.html with its own title, description,
// canonical and og tags, so the raw head is already right.
//
// Runs after cachebust.js (it copies the stamped index.html). Idempotent.
// OUT_DIR overrides where the pages + sitemap go (tests use a temp dir).
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.join(__dirname, '..');
const ORIGIN = 'https://tonightnyc.com';
const OUT_DIR = process.env.OUT_DIR || path.join(ROOT, 'public');

function fail(msg) {
  console.error(`build-pages: ${msg}`);
  process.exit(1);
}

function loadViewMeta() {
  const src = fs.readFileSync(path.join(ROOT, 'src/init.js'), 'utf8');
  const m = src.match(/const VIEW_META = (\{[\s\S]*?\n\});/);
  if (!m) fail('no `const VIEW_META = { ... };` block in src/init.js');
  const meta = vm.runInNewContext(`(${m[1]})`);
  for (const [key, e] of Object.entries(meta)) {
    for (const field of ['path', 'title', 'description']) {
      if (typeof e[field] !== 'string' || !e[field]) fail(`VIEW_META['${key}'] has no ${field}`);
    }
  }
  if (!meta.all || meta.all.path !== '/') fail("VIEW_META['all'] must have path '/'");
  return meta;
}

const escAttr = (s) => s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
const escText = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;');

// Each rule must match exactly once in index.html, or the build fails — a
// silent miss would ship a venue page that still claims to be the home page.
function venuePage(html, entry) {
  const url = ORIGIN + entry.path;
  const title = escAttr(entry.title);
  const desc = escAttr(entry.description);
  const rules = [
    [/<title>[^<]*<\/title>/g, `<title>${escText(entry.title)}</title>`],
    [/<meta property="og:title" content="[^"]*">/g, `<meta property="og:title" content="${title}">`],
    [/<meta name="twitter:title" content="[^"]*">/g, `<meta name="twitter:title" content="${title}">`],
    [/<meta property="og:url" content="[^"]*">/g, `<meta property="og:url" content="${url}">`],
    [/<link rel="canonical" href="[^"]*">/g, `<link rel="canonical" href="${url}">`],
    [/<meta name="description" content="[^"]*">/g, `<meta name="description" content="${desc}">`],
    [/<meta property="og:description" content="[^"]*">/g, `<meta property="og:description" content="${desc}">`],
    [/<meta name="twitter:description" content="[^"]*">/g, `<meta name="twitter:description" content="${desc}">`],
  ];
  let out = html;
  for (const [re, replacement] of rules) {
    const hits = (out.match(re) || []).length;
    if (hits !== 1) fail(`${re} matched ${hits} times in index.html (want 1) for ${entry.path}`);
    out = out.replace(re, () => replacement);
  }
  return out;
}

// Same changefreq/priority the hand-written sitemap used.
function sitemapEntry(entry) {
  if (entry.path === '/') return { loc: ORIGIN, changefreq: 'daily', priority: '1.0' };
  if (entry.path === '/tonight') return { loc: ORIGIN + entry.path, changefreq: 'daily', priority: '0.9' };
  if (entry.path === '/comics') return { loc: ORIGIN + entry.path, changefreq: 'daily', priority: '0.7' };
  return { loc: ORIGIN + entry.path, changefreq: 'daily', priority: '0.8' };
}

function sitemap(meta) {
  const urls = Object.values(meta).map(sitemapEntry).concat([
    { loc: `${ORIGIN}/support`, changefreq: 'monthly', priority: '0.3' },
    { loc: `${ORIGIN}/privacy`, changefreq: 'monthly', priority: '0.3' },
  ]);
  const body = urls.map((u) =>
    `  <url>\n    <loc>${u.loc}</loc>\n    <changefreq>${u.changefreq}</changefreq>\n    <priority>${u.priority}</priority>\n  </url>\n`
  ).join('');
  return `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<!-- Generated by scripts/build-pages.js from VIEW_META in src/init.js. Do not edit by hand. -->\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}</urlset>\n`;
}

function main() {
  const meta = loadViewMeta();
  const html = fs.readFileSync(path.join(ROOT, 'public/index.html'), 'utf8');
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const written = [];
  for (const [key, entry] of Object.entries(meta)) {
    if (key === 'all') continue;
    const slug = entry.path.replace(/^\//, '');
    if (!/^[a-z0-9-]+$/.test(slug)) fail(`VIEW_META['${key}'].path '${entry.path}' is not a simple /slug`);
    fs.writeFileSync(path.join(OUT_DIR, `${slug}.html`), venuePage(html, entry));
    written.push(`${slug}.html`);
  }
  fs.writeFileSync(path.join(OUT_DIR, 'sitemap.xml'), sitemap(meta));
  console.log(`build-pages: wrote ${written.length} venue pages + sitemap.xml to ${path.relative(ROOT, OUT_DIR) || '.'}`);
}

main();
